apiVersion: apps/v1
kind: Deployment
metadata:
  name: gothenburg-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gothenburg-weather
  template:
    metadata:
      labels:
        app: gothenburg-weather
    spec:
      containers:
        - name: gothenburg-weather
          image: deepikaelangovan2811/gothenburg-weather:0.20260419.6  # replaced by CI/CD pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: weather-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"